### ISSUE TITLE
Missing parameter 'name': messages with role 'function' must have a 'name'.

### ISSUE THREAD

**Issue by sbesnard** [trevorwang/openai_dart#17]
Hello,
thank you for the nice package, and the reactive inclusion of `functions`.

I get an error when I call them though...
I am adding some `ChatMessage`s to the `messages` of my `ChatCompletionRequest`, but when I add an example, I get the following error : 

`Error while processing output :OpenaiException(code: 400, error: OpenaiError(code: null, param: messages.[2].name, message: Missing parameter 'name': messages with role 'function' must have a 'name'., type: invalid_request_error))`

source code : 
```
ChatCompletionRequest(
            model: Model.gpt3_5Turbo_0613,
            messages: [
              ...
              ChatMessage(functionCall: {
                "name": "get_data_constants",
                "arguments": jsonEncode({
                  "constants": [
                    {
                      "type": "weight",
                      "value": "76,500",
                      "unit": "kg",
                      "original_text": "Weight is 76kg500",
                      "corrected_text": "Weight 76,500 kg"
                    }
                  ]
                })
              }, content: 'OK', role: ChatMessageRole.function),
              ```
              
Thanks for your help.

**Comment by trevorwang** [comment]
https://github.com/trevorwang/openai_dart/blob/50f8e6db072f804e270e5277c4ac0307fd4fa197/example/main.dart#L92

This should be fixed in latest version
